# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-06 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
