# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-06 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomco', '0002_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.CharField(default='[]', max_length=10000),
        ),
    ]
