# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-15 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='confirmation_token',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
